-- Migration 020: Create Seed Data
-- Description: SMS templates and initial configuration data
-- Dependencies: 013 (notifications tables), 015 (admin tables)

-- Update SMS template seed data with Habesha Connect branding
INSERT INTO sms_templates (template_key, template_name, content_amharic, content_english, variables) VALUES
('otp_login', 'OTP Login', 
 'Habesha Connect: የመግቢያ ኮድዎ {otp} ነው። ከ5 ደቂቃ በኋላ ያበቃል።', 
 'Habesha Connect: Your login code is {otp}. Expires in 5 minutes.',
 ARRAY['otp']),
('otp_registration', 'OTP Registration',
 'Habesha Connect: እንኳን ደህና መጡ! የምዝገባ ኮድዎ {otp} ነው።',
 'Habesha Connect: Welcome! Your registration code is {otp}.',
 ARRAY['otp']),
('otp_payment', 'OTP Payment Confirmation',
 'Habesha Connect: የክፍያ ማረጋገጫ ኮድዎ {otp} ነው። መጠን: {amount} ETB',
 'Habesha Connect: Your payment confirmation code is {otp}. Amount: {amount} ETB',
 ARRAY['otp', 'amount']),
('job_match', 'Job Match Notification',
 'Habesha Connect: Job {job_id} | {trade} | {job_type} | {price} ETB | {area}. Client: {trust_level}. Reply ACCEPT {job_id} or REJECT {job_id}',
 'Habesha Connect: Job {job_id} | {trade} | {job_type} | {price} ETB | {area}. Client: {trust_level}. Reply ACCEPT {job_id} or REJECT {job_id}',
 ARRAY['job_id', 'trade', 'job_type', 'price', 'area', 'trust_level']),
('job_accepted_worker', 'Job Accepted (Worker)',
 'You accepted job {job_id}. Client: {client_name}, {client_phone}, {address}. Date: {date} {time}. Platform not liable for work quality/disputes.', 
 'You accepted job {job_id}. Client: {client_name}, {client_phone}, {address}. Date: {date} {time}. Platform not liable for work quality/disputes.',
 ARRAY['job_id', 'client_name', 'client_phone', 'address', 'date', 'time']),
('job_accepted_client', 'Job Accepted (Client)',
 'Worker {worker_name} accepted your job {job_id}. Phone: {worker_phone}. Rating: {rating}/5. Date: {date} {time}.',
 'Worker {worker_name} accepted your job {job_id}. Phone: {worker_phone}. Rating: {rating}/5. Date: {date} {time}.',
 ARRAY['worker_name', 'job_id', 'worker_phone', 'rating', 'date', 'time']),
('reminder', 'Job Reminder',
 'Habesha Connect: Reminder! Job {job_id} in 1 hour. {role}: {name}, {phone}.',
 'Habesha Connect: Reminder! Job {job_id} in 1 hour. {role}: {name}, {phone}.',
 ARRAY['job_id', 'role', 'name', 'phone']),
('payment_confirmation', 'Payment Confirmation',
 'Payment of {amount} ETB received for job {job_id}. Receipt: {receipt_url}. Thank you for using Habesha Connect!',
 'Payment of {amount} ETB received for job {job_id}. Receipt: {receipt_url}. Thank you for using Habesha Connect!',
 ARRAY['amount', 'job_id', 'receipt_url']),
('rating_request', 'Rating Request',
 'Please rate your {role} for job {job_id}. Reply RATE {job_id} {rating} or visit {url}',
 'Please rate your {role} for job {job_id}. Reply RATE {job_id} {rating} or visit {url}',
 ARRAY['role', 'job_id', 'rating', 'url']),
('verification_approved', 'Verification Approved',
 'Congratulations! Your {trade} verification has been approved. You can now receive job matches on Habesha Connect.',
 'Congratulations! Your {trade} verification has been approved. You can now receive job matches on Habesha Connect.',
 ARRAY['trade']),
('verification_revoked', 'Verification Revoked',
 'Your {trade} verification has been revoked. Reason: {reason}. Contact support@habeshaconnect.com for more information.',
 'Your {trade} verification has been revoked. Reason: {reason}. Contact support@habeshaconnect.com for more information.',
 ARRAY['trade', 'reason']),
('verification_scheduled', 'Verification Scheduled',
 'Your {trade} verification is scheduled for {date} at {time}. Location: {location}. Please bring your tools.',
 'Your {trade} verification is scheduled for {date} at {time}. Location: {location}. Please bring your tools.',
 ARRAY['trade', 'date', 'time', 'location']),
('dispute_filed', 'Dispute Filed',
 'A dispute has been filed for job {job_id}. Admin will review within 48 hours. Reference: {dispute_id}',
 'A dispute has been filed for job {job_id}. Admin will review within 48 hours. Reference: {dispute_id}',
 ARRAY['job_id', 'dispute_id']),
('welcome_client', 'Welcome Client',
 'Welcome to Habesha Connect! Find verified workers for your projects. Post your first job at {url}',
 'Welcome to Habesha Connect! Find verified workers for your projects. Post your first job at {url}',
 ARRAY['url']),
('welcome_worker', 'Welcome Worker',
 'Welcome to Habesha Connect! Get verified and start receiving job matches. Complete your profile at {url}',
 'Welcome to Habesha Connect! Get verified and start receiving job matches. Complete your profile at {url}',
 ARRAY['url']);